/* PART 1: STATE */
const KEY='bplugins_state_v2';
const state=JSON.parse(localStorage.getItem(KEY)||'null')||{users:[],session:null,plugins:[],trades:[],votes:{}};
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function toast(msg){const n=$('#toast');if(!n)return;n.textContent=msg;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2800);}
function uid(prefix='ID'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
function user(){return state.users.find(x=>x.id===state.session)||null;}
function needUser(){if(!user()){openDialog('accountDialog');toast('Artist Core access required.');return false;}return true;}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

/* PART 2: GALLERY + AUDIO */
function switchWing(id){$$('.wing').forEach(x=>x.classList.toggle('visible',x.id===id));$$('.wing').forEach(x=>x.classList.toggle('hidden',x.id!==id));$$('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.wing===id));history.replaceState(null,'',`#${id}`);if(id==='shop')renderShop();if(id==='contact')renderTrades();}
let audioCtx,osc,filter,gain;
function toggleDrone(){const glow=$('#ambientGlow'),btn=$('#auditionBtn');if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();filter=audioCtx.createBiquadFilter();gain=audioCtx.createGain();osc.type='sawtooth';osc.frequency.value=55;filter.type='lowpass';filter.frequency.value=140;gain.gain.value=.08;osc.connect(filter).connect(gain).connect(audioCtx.destination);osc.start();glow?.classList.add('active-drone');btn.textContent='[MUTE_CANVAS_DRONE]';return;}if(audioCtx.state==='running'){audioCtx.suspend();glow?.classList.remove('active-drone');btn.textContent='[AUDITION_CANVAS_SIGNATURE]';}else{audioCtx.resume();glow?.classList.add('active-drone');btn.textContent='[MUTE_CANVAS_DRONE]';}}
function tier(score){return score>=100?'Elite':score>=50?'Artisan':'Exhibition';}
function value(score){return Math.max(1,100+score*5);}
function renderShop(){const box=$('#publicRegistry');if(!box)return;const q=($('#shopSearch')?.value||'').toLowerCase();let rows=state.plugins.filter(p=>`${p.name} ${p.creator} ${p.category} ${p.description}`.toLowerCase().includes(q));const sort=$('#shopSort')?.value||'score';rows.sort((a,b)=>sort==='value'?value(b.score)-value(a.score):sort==='new'?b.created-a.created:b.score-a.score);$('#emptyShop')?.classList.toggle('hidden',rows.length>0);box.innerHTML=rows.map(p=>{const t=tier(p.score);return `<article class="plugin-card ${t.toLowerCase()}" data-score="${p.score}"><div class="plugin-art" style="${p.image?'background-image:url('+p.image+')':''}"><span>${esc(p.category)}</span><b>${esc(t)}</b></div><div class="plugin-body"><div class="plugin-top"><h3>${esc(p.name)}</h3><small>BY ${esc(p.creator)}</small></div><p>${esc(p.description)}</p><div class="metric-row"><strong>${p.score} APPLAUSE</strong><strong>$${value(p.score)}</strong></div><div class="card-actions"><button class="primary-btn small" data-applaud="${p.id}">[APPLAUD_ONCE]</button><button class="ghost-btn small" data-detail="${p.id}">[OPEN]</button></div></div></article>`}).join('');}
function openDetail(id){const p=state.plugins.find(x=>x.id===id);if(!p)return;const comments=p.comments||[];$('#detailContent').innerHTML=`<span class="eyebrow">EXHIBIT // ${esc(p.category)}</span><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p>${p.audio?`<audio controls src="${p.audio}"></audio>`:''}<p class="detail-meta">BY ${esc(p.creator)} · ${p.score} APPLAUSE · $${value(p.score)}</p><a class="primary-btn small" href="${p.file}" download="${esc(p.fileName)}">[DOWNLOAD_PLUGIN]</a><hr><h3>COMMITMENTS</h3><div id="comments">${comments.map(c=>`<p class="comment"><b>${esc(c.by)}</b> ${esc(c.text)}</p>`).join('')}</div>${user()?`<form id="commentForm"><input id="commentText" maxlength="500" required placeholder="Leave a commitment…"><button class="primary-btn small">[COMMIT]</button></form>`:'<p>Sign in to commit on this exhibit.</p>'}`;$('#detailDialog').showModal();$('#commentForm')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#commentText').value.trim();if(!text)return;p.comments=p.comments||[];p.comments.push({by:user().handle,text});save();openDetail(p.id);});}
function applaud(id,btn){if(!needUser())return;const key=`${user().id}:${id}`;if(state.votes[key])return toast('You already applauded this exhibit.');const p=state.plugins.find(x=>x.id===id);if(!p)return;state.votes[key]=1;p.score++;save();renderShop();updateStats();toast(`${p.name} received applause.`);}

/* PART 3: ACCOUNTS, UPLOADS, TRADES */
function openDialog(id){$(id)?.showModal();}
function addTradeInput(kind){const wrap=kind==='out'?$('#outgoingList'):$('#seekingList');const input=document.createElement('input');input.className=`trade-${kind}`;input.required=true;input.placeholder=kind==='out'?'Plugin you offer':'Plugin you seek';wrap.appendChild(input);}
function renderTrades(){const box=$('#tradeFeed');if(!box)return;box.innerHTML=state.trades.slice().reverse().slice(0,12).map(t=>`<article class="trade-item"><b>${esc(t.artist)}</b> · ${t.out.length} → ${t.seek.length}<p>${esc(t.note||'Open exchange')}</p></article>`).join('')||'<p class="muted">No trades yet.</p>';}
function updateStats(){$('#statPlugins')&&( $('#statPlugins').textContent=state.plugins.length);$('#statArtists')&&( $('#statArtists').textContent=new Set(state.plugins.map(p=>p.creator)).size);$('#statTrades')&&( $('#statTrades').textContent=state.trades.length);$('#statApplause')&&( $('#statApplause').textContent=state.plugins.reduce((n,p)=>n+p.score,0));const u=user();$('#accountLabel')&&($('#accountLabel').textContent=u?`ARTIST // ${u.handle}`:'GUEST // NO_SESSION');}
function bind(){switchWing(location.hash.slice(1)||'home');$$('[data-wing]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();switchWing(a.dataset.wing)}));$('#auditionBtn')?.addEventListener('click',toggleDrone);$('#accountBtn')?.addEventListener('click',()=>openDialog('accountDialog'));$('#heroAccountBtn')?.addEventListener('click',()=>openDialog('accountDialog'));$('#openUploadBtn')?.addEventListener('click',()=>needUser()&&openDialog('uploadDialog'));$('#shopSearch')?.addEventListener('input',renderShop);$('#shopSort')?.addEventListener('change',renderShop);$('#addOutgoing')?.addEventListener('click',()=>addTradeInput('out'));$('#addSeeking')?.addEventListener('click',()=>addTradeInput('seek'));addTradeInput('out');addTradeInput('seek');$$('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));$('#authForm')?.addEventListener('submit',e=>{e.preventDefault();const h=$('#authHandle').value.trim(),em=$('#authEmail').value.trim().toLowerCase(),pw=$('#authPassword').value;if(state.users.some(u=>u.email===em))return toast('Email already exists.');state.users.push({id:uid('USR'),handle:h,email:em,password:pw});state.session=state.users.at(-1).id;save();$('#accountDialog').close();updateStats();toast(`Welcome, ${h}.`);});$('#uploadForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!needUser())return;const file=$('#pluginFile').files[0],audio=$('#pluginAudio').files[0],img=$('#pluginImage').files[0];if(!file||!audio)return;const read=f=>new Promise(r=>{const x=new FileReader();x.onload=()=>r(x.result);x.readAsDataURL(f)});const p={id:uid('PLG'),name:$('#pluginName').value.trim(),category:$('#pluginCategory').value.trim(),description:$('#pluginDescription').value.trim(),creator:user().handle,score:0,created:Date.now(),file:await read(file),fileName:file.name,audio:await read(audio),image:img?await read(img):'',comments:[]};state.plugins.push(p);save();$('#uploadDialog').close();e.target.reset();renderShop();updateStats();toast('Exhibit published to this browser.');});$('#tradeForm')?.addEventListener('submit',e=>{e.preventDefault();if(!needUser())return;const out=$$('.trade-out').map(x=>x.value.trim()).filter(Boolean),seek=$$('.trade-seek').map(x=>x.value.trim()).filter(Boolean);state.trades.push({id:uid('TRD'),artist:user().handle,out,seek,note:$('#tradeNote').value.trim(),created:Date.now()});save();e.target.reset();$('#outgoingList').innerHTML='';$('#seekingList').innerHTML='';addTradeInput('out');addTradeInput('seek');renderTrades();updateStats();toast('Barter package staged.');});$('#publicRegistry')?.addEventListener('click',e=>{const a=e.target.closest('[data-applaud]');const d=e.target.closest('[data-detail]');if(a)applaud(a.dataset.applaud,a);if(d)openDetail(d.dataset.detail);});updateStats();renderShop();renderTrades();}
document.addEventListener('DOMContentLoaded',bind);